### ISSUE TITLE
please don't call curl_init directly.

### ISSUE THREAD

**Issue by danmarsden** [sit-alemira/alemira-proctor-moodle-plugin#8]
Please don't initate curl_init() directly but use Moodle's own "curl" class which is a wrapper on PHP's curl functions which perform various security checks and many organisations put their moodle site behind a web proxy and the internal curl wrapper takes care of this for you. 

it's not documented well though - do a search on moodle code for curl() to find examples of it's use.

**Comment by MaksimBurnin** [comment]
Fixed in 1697e74
